//go:build go1.22

// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CalculationRequestOperation.
const (
	Add      CalculationRequestOperation = "add"
	Divide   CalculationRequestOperation = "divide"
	Multiply CalculationRequestOperation = "multiply"
	Subtract CalculationRequestOperation = "subtract"
)

// Valid indicates whether the value is a known member of the CalculationRequestOperation enum.
func (e CalculationRequestOperation) Valid() bool {
	switch e {
	case Add:
		return true
	case Divide:
		return true
	case Multiply:
		return true
	case Subtract:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatusStatus.
const (
	HealthStatusStatusOk HealthStatusStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatusStatus enum.
func (e HealthStatusStatus) Valid() bool {
	switch e {
	case HealthStatusStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for ReadinessStatusStatus.
const (
	ReadinessStatusStatusDegraded ReadinessStatusStatus = "degraded"
	ReadinessStatusStatusOk       ReadinessStatusStatus = "ok"
)

// Valid indicates whether the value is a known member of the ReadinessStatusStatus enum.
func (e ReadinessStatusStatus) Valid() bool {
	switch e {
	case ReadinessStatusStatusDegraded:
		return true
	case ReadinessStatusStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for TokenPairTokenType.
const (
	Bearer TokenPairTokenType = "Bearer"
)

// Valid indicates whether the value is a known member of the TokenPairTokenType enum.
func (e TokenPairTokenType) Valid() bool {
	switch e {
	case Bearer:
		return true
	default:
		return false
	}
}

// Defines values for ClientPlatform.
const (
	ClientPlatformAndroid ClientPlatform = "android"
	ClientPlatformIos     ClientPlatform = "ios"
	ClientPlatformWeb     ClientPlatform = "web"
)

// Valid indicates whether the value is a known member of the ClientPlatform enum.
func (e ClientPlatform) Valid() bool {
	switch e {
	case ClientPlatformAndroid:
		return true
	case ClientPlatformIos:
		return true
	case ClientPlatformWeb:
		return true
	default:
		return false
	}
}

// Defines values for LoginUserParamsXClientPlatform.
const (
	LoginUserParamsXClientPlatformAndroid LoginUserParamsXClientPlatform = "android"
	LoginUserParamsXClientPlatformIos     LoginUserParamsXClientPlatform = "ios"
	LoginUserParamsXClientPlatformWeb     LoginUserParamsXClientPlatform = "web"
)

// Valid indicates whether the value is a known member of the LoginUserParamsXClientPlatform enum.
func (e LoginUserParamsXClientPlatform) Valid() bool {
	switch e {
	case LoginUserParamsXClientPlatformAndroid:
		return true
	case LoginUserParamsXClientPlatformIos:
		return true
	case LoginUserParamsXClientPlatformWeb:
		return true
	default:
		return false
	}
}

// Defines values for RefreshSessionParamsXClientPlatform.
const (
	RefreshSessionParamsXClientPlatformAndroid RefreshSessionParamsXClientPlatform = "android"
	RefreshSessionParamsXClientPlatformIos     RefreshSessionParamsXClientPlatform = "ios"
	RefreshSessionParamsXClientPlatformWeb     RefreshSessionParamsXClientPlatform = "web"
)

// Valid indicates whether the value is a known member of the RefreshSessionParamsXClientPlatform enum.
func (e RefreshSessionParamsXClientPlatform) Valid() bool {
	switch e {
	case RefreshSessionParamsXClientPlatformAndroid:
		return true
	case RefreshSessionParamsXClientPlatformIos:
		return true
	case RefreshSessionParamsXClientPlatformWeb:
		return true
	default:
		return false
	}
}

// AuthMethods What the client needs to decide between "Set password" and "Change
// password", and when to disable unlinking.
type AuthMethods struct {
	Identities []Identity `json:"identities"`
	Password   bool       `json:"password"`
}

// CalculationRequest defines model for CalculationRequest.
type CalculationRequest struct {
	// A A decimal number, sent as a string on purpose. A JSON number is decoded
	// into a float64 before any server code runs, and 0.1 + 0.2 is already
	// wrong by that point. The length cap keeps a single request from asking
	// for arbitrarily large arithmetic.
	//
	//
	// Example: 10.5
	A Operand `json:"a"`

	// B A decimal number, sent as a string on purpose. A JSON number is decoded
	// into a float64 before any server code runs, and 0.1 + 0.2 is already
	// wrong by that point. The length cap keeps a single request from asking
	// for arbitrarily large arithmetic.
	//
	//
	// Example: 10.5
	B         Operand                     `json:"b"`
	Operation CalculationRequestOperation `json:"operation"`
}

// CalculationRequestOperation defines model for CalculationRequest.Operation.
type CalculationRequestOperation string

// CalculationResult defines model for CalculationResult.
type CalculationResult struct {
	// Result Example: 13.5
	Result string `json:"result"`
}

// Error defines model for Error.
type Error struct {
	// Code Stable code for clients to branch on. Never changes once released.
	//
	//
	// Example: ERR_AUTH_INVALID_CREDENTIALS
	Code string `json:"code"`

	// Details Per-field errors, for validation failures.
	Details *[]ErrorDetail `json:"details,omitempty"`

	// Message Human-readable. NOT a contract, may change at any time.
	Message string `json:"message"`
}

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	Field   string `json:"field"`
	Message string `json:"message"`
}

// HealthStatus defines model for HealthStatus.
type HealthStatus struct {
	Status HealthStatusStatus `json:"status"`
}

// HealthStatusStatus defines model for HealthStatus.Status.
type HealthStatusStatus string

// Identity defines model for Identity.
type Identity struct {
	Email *string            `json:"email,omitempty"`
	Id    openapi_types.UUID `json:"id"`

	// Provider Example: google
	Provider string `json:"provider"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	// Email Example: someone@example.com
	Email    string `json:"email"`
	Password string `json:"password"`
}

// Me defines model for Me.
type Me struct {
	// AuthMethods What the client needs to decide between "Set password" and "Change
	// password", and when to disable unlinking.
	AuthMethods   AuthMethods         `json:"auth_methods"`
	Email         openapi_types.Email `json:"email"`
	EmailVerified bool                `json:"email_verified"`
	Id            openapi_types.UUID  `json:"id"`
}

// Operand A decimal number, sent as a string on purpose. A JSON number is decoded
// into a float64 before any server code runs, and 0.1 + 0.2 is already
// wrong by that point. The length cap keeps a single request from asking
// for arbitrarily large arithmetic.
//
// Example: 10.5
type Operand = string

// ReadinessCheck defines model for ReadinessCheck.
type ReadinessCheck struct {
	// Error Set only when ok=false. Never carries internal detail.
	Error *string `json:"error,omitempty"`

	// Name Example: postgres
	Name string `json:"name"`
	Ok   bool   `json:"ok"`
}

// ReadinessStatus defines model for ReadinessStatus.
type ReadinessStatus struct {
	Checks []ReadinessCheck      `json:"checks"`
	Status ReadinessStatusStatus `json:"status"`
}

// ReadinessStatusStatus defines model for ReadinessStatus.Status.
type ReadinessStatusStatus string

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	// RefreshToken For clients that hold the token themselves. Web clients omit it
	// because the cookie carries it.
	RefreshToken *string `json:"refresh_token,omitempty"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	// Email Example: someone@example.com
	Email string `json:"email"`

	// Password Minimum 12 characters. Length is the only rule: composition rules
	// push people towards predictable substitutions.
	Password string `json:"password"`
}

// RegisteredUser defines model for RegisteredUser.
type RegisteredUser struct {
	Email         openapi_types.Email `json:"email"`
	EmailVerified bool                `json:"email_verified"`
	Id            openapi_types.UUID  `json:"id"`
}

// TokenPair defines model for TokenPair.
type TokenPair struct {
	AccessToken string `json:"access_token"`

	// ExpiresIn Seconds until the access token expires.
	//
	// Example: 900
	ExpiresIn int `json:"expires_in"`

	// RefreshToken Absent for web clients: they receive it in an httpOnly cookie
	// instead, which a script cannot read.
	RefreshToken *string            `json:"refresh_token,omitempty"`
	TokenType    TokenPairTokenType `json:"token_type"`
}

// TokenPairTokenType defines model for TokenPair.TokenType.
type TokenPairTokenType string

// VerifyEmailRequest defines model for VerifyEmailRequest.
type VerifyEmailRequest struct {
	Token string `json:"token"`
}

// ClientPlatform defines model for ClientPlatform.
type ClientPlatform string

// RefreshCookie defines model for RefreshCookie.
type RefreshCookie = string

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// ValidationFailed defines model for ValidationFailed.
type ValidationFailed = Error

// LoginUserParams defines parameters for LoginUser.
type LoginUserParams struct {
	// XClientPlatform Decides how the refresh token is delivered. "web" gets it in an
	// httpOnly cookie and never in the response body, so a script cannot read
	// it. Anything else gets it in the body to put in secure storage.
	XClientPlatform *LoginUserParamsXClientPlatform `json:"X-Client-Platform,omitempty"`
}

// LoginUserParamsXClientPlatform defines parameters for LoginUser.
type LoginUserParamsXClientPlatform string

// LogoutParams defines parameters for Logout.
type LogoutParams struct {
	// RefreshToken Where web clients carry the refresh token. Declared here so the cookie
	// is part of the contract rather than an undocumented side channel.
	RefreshToken *RefreshCookie `form:"refresh_token,omitempty" json:"refresh_token,omitempty"`
}

// RefreshSessionParams defines parameters for RefreshSession.
type RefreshSessionParams struct {
	// XClientPlatform Decides how the refresh token is delivered. "web" gets it in an
	// httpOnly cookie and never in the response body, so a script cannot read
	// it. Anything else gets it in the body to put in secure storage.
	XClientPlatform *RefreshSessionParamsXClientPlatform `json:"X-Client-Platform,omitempty"`

	// RefreshToken Where web clients carry the refresh token. Declared here so the cookie
	// is part of the contract rather than an undocumented side channel.
	RefreshToken *RefreshCookie `form:"refresh_token,omitempty" json:"refresh_token,omitempty"`
}

// RefreshSessionParamsXClientPlatform defines parameters for RefreshSession.
type RefreshSessionParamsXClientPlatform string

// LoginUserJSONRequestBody defines body for LoginUser for application/json ContentType.
type LoginUserJSONRequestBody = LoginRequest

// LogoutJSONRequestBody defines body for Logout for application/json ContentType.
type LogoutJSONRequestBody = RefreshRequest

// RefreshSessionJSONRequestBody defines body for RefreshSession for application/json ContentType.
type RefreshSessionJSONRequestBody = RefreshRequest

// RegisterUserJSONRequestBody defines body for RegisterUser for application/json ContentType.
type RegisterUserJSONRequestBody = RegisterRequest

// VerifyEmailJSONRequestBody defines body for VerifyEmail for application/json ContentType.
type VerifyEmailJSONRequestBody = VerifyEmailRequest

// CalculateJSONRequestBody defines body for Calculate for application/json ContentType.
type CalculateJSONRequestBody = CalculationRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetHealthz Liveness probe
	// (GET /healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)
	// GetReadyz Readiness probe
	// (GET /readyz)
	GetReadyz(w http.ResponseWriter, r *http.Request)
	// LoginUser Exchange email and password for an access token
	// (POST /v1/auth/login)
	LoginUser(w http.ResponseWriter, r *http.Request, params LoginUserParams)
	// Logout End the session
	// (POST /v1/auth/logout)
	Logout(w http.ResponseWriter, r *http.Request, params LogoutParams)
	// RefreshSession Rotate the refresh token and get a new access token
	// (POST /v1/auth/refresh)
	RefreshSession(w http.ResponseWriter, r *http.Request, params RefreshSessionParams)
	// RegisterUser Create an account with an email and password
	// (POST /v1/auth/register)
	RegisterUser(w http.ResponseWriter, r *http.Request)
	// VerifyEmail Confirm an email address with a token
	// (POST /v1/auth/verify-email)
	VerifyEmail(w http.ResponseWriter, r *http.Request)
	// Calculate Evaluate one arithmetic operation
	// (POST /v1/calculations)
	Calculate(w http.ResponseWriter, r *http.Request)
	// GetMe The authenticated user and its active login methods
	// (GET /v1/me)
	GetMe(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReadyz operation middleware
func (siw *ServerInterfaceWrapper) GetReadyz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadyz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LoginUser operation middleware
func (siw *ServerInterfaceWrapper) LoginUser(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params LoginUserParams

	headers := r.Header

	// ------------- Optional header parameter "X-Client-Platform" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Client-Platform")]; found {
		var XClientPlatform LoginUserParamsXClientPlatform
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Client-Platform", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Client-Platform", valueList[0], &XClientPlatform, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Client-Platform", Err: err})
			return
		}

		params.XClientPlatform = &XClientPlatform

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LoginUser(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params LogoutParams

	{
		var cookie *http.Cookie

		if cookie, err = r.Cookie("refresh_token"); err == nil {
			var value RefreshCookie
			err = runtime.BindStyledParameterWithOptions("simple", "refresh_token", cookie.Value, &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationCookie, Explode: true, Required: false, Type: "string", Format: ""})
			if err != nil {
				siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "refresh_token", Err: err})
				return
			}
			params.RefreshToken = &value

		}
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RefreshSession operation middleware
func (siw *ServerInterfaceWrapper) RefreshSession(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params RefreshSessionParams

	headers := r.Header

	// ------------- Optional header parameter "X-Client-Platform" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Client-Platform")]; found {
		var XClientPlatform RefreshSessionParamsXClientPlatform
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Client-Platform", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Client-Platform", valueList[0], &XClientPlatform, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Client-Platform", Err: err})
			return
		}

		params.XClientPlatform = &XClientPlatform

	}

	{
		var cookie *http.Cookie

		if cookie, err = r.Cookie("refresh_token"); err == nil {
			var value RefreshCookie
			err = runtime.BindStyledParameterWithOptions("simple", "refresh_token", cookie.Value, &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationCookie, Explode: true, Required: false, Type: "string", Format: ""})
			if err != nil {
				siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "refresh_token", Err: err})
				return
			}
			params.RefreshToken = &value

		}
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RefreshSession(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RegisterUser operation middleware
func (siw *ServerInterfaceWrapper) RegisterUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// VerifyEmail operation middleware
func (siw *ServerInterfaceWrapper) VerifyEmail(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.VerifyEmail(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Calculate operation middleware
func (siw *ServerInterfaceWrapper) Calculate(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Calculate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/auth/register", wrapper.RegisterUser)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/auth/login", wrapper.LoginUser)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/auth/refresh", wrapper.RefreshSession)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/auth/logout", wrapper.Logout)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/auth/verify-email", wrapper.VerifyEmail)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/me", wrapper.GetMe)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/calculations", wrapper.Calculate)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/healthz", wrapper.GetHealthz)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/readyz", wrapper.GetReadyz)

	return m
}

type BadRequestJSONResponse Error

type ConflictJSONResponse Error

type ForbiddenJSONResponse Error

type TooManyRequestsJSONResponse Error

type UnauthorizedJSONResponse Error

type ValidationFailedJSONResponse Error

type GetHealthzRequestObject struct {
}

type GetHealthzResponseObject interface {
	VisitGetHealthzResponse(w http.ResponseWriter) error
}

type GetHealthz200JSONResponse HealthStatus

func (response GetHealthz200JSONResponse) VisitGetHealthzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadyzRequestObject struct {
}

type GetReadyzResponseObject interface {
	VisitGetReadyzResponse(w http.ResponseWriter) error
}

type GetReadyz200JSONResponse ReadinessStatus

func (response GetReadyz200JSONResponse) VisitGetReadyzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadyz503JSONResponse ReadinessStatus

func (response GetReadyz503JSONResponse) VisitGetReadyzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type LoginUserRequestObject struct {
	Params LoginUserParams
	Body   *LoginUserJSONRequestBody
}

type LoginUserResponseObject interface {
	VisitLoginUserResponse(w http.ResponseWriter) error
}

type LoginUser200JSONResponse TokenPair

func (response LoginUser200JSONResponse) VisitLoginUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type LoginUser400JSONResponse struct{ BadRequestJSONResponse }

func (response LoginUser400JSONResponse) VisitLoginUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type LoginUser401JSONResponse Error

func (response LoginUser401JSONResponse) VisitLoginUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type LoginUser403JSONResponse struct{ ForbiddenJSONResponse }

func (response LoginUser403JSONResponse) VisitLoginUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type LoginUser429JSONResponse struct{ TooManyRequestsJSONResponse }

func (response LoginUser429JSONResponse) VisitLoginUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type LogoutRequestObject struct {
	Params LogoutParams
	Body   *LogoutJSONRequestBody
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout204Response struct {
}

func (response Logout204Response) VisitLogoutResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type RefreshSessionRequestObject struct {
	Params RefreshSessionParams
	Body   *RefreshSessionJSONRequestBody
}

type RefreshSessionResponseObject interface {
	VisitRefreshSessionResponse(w http.ResponseWriter) error
}

type RefreshSession200JSONResponse TokenPair

func (response RefreshSession200JSONResponse) VisitRefreshSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshSession400JSONResponse struct{ BadRequestJSONResponse }

func (response RefreshSession400JSONResponse) VisitRefreshSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshSession401JSONResponse Error

func (response RefreshSession401JSONResponse) VisitRefreshSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterUserRequestObject struct {
	Body *RegisterUserJSONRequestBody
}

type RegisterUserResponseObject interface {
	VisitRegisterUserResponse(w http.ResponseWriter) error
}

type RegisterUser201JSONResponse RegisteredUser

func (response RegisterUser201JSONResponse) VisitRegisterUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterUser400JSONResponse struct{ BadRequestJSONResponse }

func (response RegisterUser400JSONResponse) VisitRegisterUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterUser409JSONResponse struct{ ConflictJSONResponse }

func (response RegisterUser409JSONResponse) VisitRegisterUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterUser422JSONResponse struct{ ValidationFailedJSONResponse }

func (response RegisterUser422JSONResponse) VisitRegisterUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type VerifyEmailRequestObject struct {
	Body *VerifyEmailJSONRequestBody
}

type VerifyEmailResponseObject interface {
	VisitVerifyEmailResponse(w http.ResponseWriter) error
}

type VerifyEmail204Response struct {
}

func (response VerifyEmail204Response) VisitVerifyEmailResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type VerifyEmail400JSONResponse struct{ BadRequestJSONResponse }

func (response VerifyEmail400JSONResponse) VisitVerifyEmailResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type VerifyEmail410JSONResponse Error

func (response VerifyEmail410JSONResponse) VisitVerifyEmailResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(410)
	_, err := buf.WriteTo(w)
	return err
}

type CalculateRequestObject struct {
	Body *CalculateJSONRequestBody
}

type CalculateResponseObject interface {
	VisitCalculateResponse(w http.ResponseWriter) error
}

type Calculate200JSONResponse CalculationResult

func (response Calculate200JSONResponse) VisitCalculateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Calculate400JSONResponse struct{ BadRequestJSONResponse }

func (response Calculate400JSONResponse) VisitCalculateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type Calculate401JSONResponse struct{ UnauthorizedJSONResponse }

func (response Calculate401JSONResponse) VisitCalculateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type Calculate422JSONResponse struct{ ValidationFailedJSONResponse }

func (response Calculate422JSONResponse) VisitCalculateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type GetMeRequestObject struct {
}

type GetMeResponseObject interface {
	VisitGetMeResponse(w http.ResponseWriter) error
}

type GetMe200JSONResponse Me

func (response GetMe200JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMe401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetMe401JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetHealthz Liveness probe
	// (GET /healthz)
	GetHealthz(ctx context.Context, request GetHealthzRequestObject) (GetHealthzResponseObject, error)
	// GetReadyz Readiness probe
	// (GET /readyz)
	GetReadyz(ctx context.Context, request GetReadyzRequestObject) (GetReadyzResponseObject, error)
	// LoginUser Exchange email and password for an access token
	// (POST /v1/auth/login)
	LoginUser(ctx context.Context, request LoginUserRequestObject) (LoginUserResponseObject, error)
	// Logout End the session
	// (POST /v1/auth/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// RefreshSession Rotate the refresh token and get a new access token
	// (POST /v1/auth/refresh)
	RefreshSession(ctx context.Context, request RefreshSessionRequestObject) (RefreshSessionResponseObject, error)
	// RegisterUser Create an account with an email and password
	// (POST /v1/auth/register)
	RegisterUser(ctx context.Context, request RegisterUserRequestObject) (RegisterUserResponseObject, error)
	// VerifyEmail Confirm an email address with a token
	// (POST /v1/auth/verify-email)
	VerifyEmail(ctx context.Context, request VerifyEmailRequestObject) (VerifyEmailResponseObject, error)
	// Calculate Evaluate one arithmetic operation
	// (POST /v1/calculations)
	Calculate(ctx context.Context, request CalculateRequestObject) (CalculateResponseObject, error)
	// GetMe The authenticated user and its active login methods
	// (GET /v1/me)
	GetMe(ctx context.Context, request GetMeRequestObject) (GetMeResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetHealthz operation middleware
func (sh *strictHandler) GetHealthz(w http.ResponseWriter, r *http.Request) {
	var request GetHealthzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealthz(ctx, request.(GetHealthzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealthz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthzResponseObject); ok {
		if err := validResponse.VisitGetHealthzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetReadyz operation middleware
func (sh *strictHandler) GetReadyz(w http.ResponseWriter, r *http.Request) {
	var request GetReadyzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetReadyz(ctx, request.(GetReadyzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReadyz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetReadyzResponseObject); ok {
		if err := validResponse.VisitGetReadyzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// LoginUser operation middleware
func (sh *strictHandler) LoginUser(w http.ResponseWriter, r *http.Request, params LoginUserParams) {
	var request LoginUserRequestObject

	request.Params = params

	var body LoginUserJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.LoginUser(ctx, request.(LoginUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LoginUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LoginUserResponseObject); ok {
		if err := validResponse.VisitLoginUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Logout operation middleware
func (sh *strictHandler) Logout(w http.ResponseWriter, r *http.Request, params LogoutParams) {
	var request LogoutRequestObject

	request.Params = params

	var body LogoutJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		if !errors.Is(err, io.EOF) {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
			return
		}
	} else {
		request.Body = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx, request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		if err := validResponse.VisitLogoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RefreshSession operation middleware
func (sh *strictHandler) RefreshSession(w http.ResponseWriter, r *http.Request, params RefreshSessionParams) {
	var request RefreshSessionRequestObject

	request.Params = params

	var body RefreshSessionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		if !errors.Is(err, io.EOF) {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
			return
		}
	} else {
		request.Body = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RefreshSession(ctx, request.(RefreshSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RefreshSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RefreshSessionResponseObject); ok {
		if err := validResponse.VisitRefreshSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RegisterUser operation middleware
func (sh *strictHandler) RegisterUser(w http.ResponseWriter, r *http.Request) {
	var request RegisterUserRequestObject

	var body RegisterUserJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RegisterUser(ctx, request.(RegisterUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RegisterUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RegisterUserResponseObject); ok {
		if err := validResponse.VisitRegisterUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// VerifyEmail operation middleware
func (sh *strictHandler) VerifyEmail(w http.ResponseWriter, r *http.Request) {
	var request VerifyEmailRequestObject

	var body VerifyEmailJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.VerifyEmail(ctx, request.(VerifyEmailRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "VerifyEmail")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(VerifyEmailResponseObject); ok {
		if err := validResponse.VisitVerifyEmailResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Calculate operation middleware
func (sh *strictHandler) Calculate(w http.ResponseWriter, r *http.Request) {
	var request CalculateRequestObject

	var body CalculateJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Calculate(ctx, request.(CalculateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Calculate")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CalculateResponseObject); ok {
		if err := validResponse.VisitCalculateResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMe operation middleware
func (sh *strictHandler) GetMe(w http.ResponseWriter, r *http.Request) {
	var request GetMeRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMe(ctx, request.(GetMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMeResponseObject); ok {
		if err := validResponse.VisitGetMeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"1Fprbxs31v4rB/O+H1rsWJadtGgFLLCO42xcxElgO80uosClhkca1hxyluRIUQv/98U5HM1FGl/axEH3",
	"mzQz5Lk/50L+nmS2KK1BE3wy+T0phRMFBnT871grNOGtFmFuXUFPJPrMqTIoa5JJ8hwzJdFDblcQcgSH",
	"c4c+h2Cv0YDyIFGrJTqUI5gmK5xNE1hg8KACKAPCTE0eQvnG6DVk1l4rBGEkGFyiow/inr60xiPMrFyn",
	"4C0IiDxAJoyxARwKOTUqjODIrEOuzAJQe+xSCnlcD8FCWfEjj1nlEHywTixwNDVJmigSKkch0SVpYkSB",
	"yST5115Uw16jhzTxWY6FIIWgqYpk8oGEow2sT9JEGOmsksnHNAnrkvbwwSmzSG5u0uQ86uiYxd1V6fsc",
	"HcIKZ5AxVQ+ZcG69q94RPMdMC4cSeIm3/E1U49QoD6VwAey8fmyCE1kAJ0KODkIuSP9QGWmzqkATUIJX",
	"EiHLhTGoOwqJW7YKqdm4YjZ6ytiW9iZNNuZjf3om5Dn+p0If6B/xhIZ/irLUKhOkg/1fPSni9862/+9w",
	"nkyS/9tvfXU/vvX7J85ZF0n1FXkmNBkLJbia5E2aHFsz1yr7CuQ3lDysVMgBPykfyDN9EAGJlRfWzZSU",
	"aB6fl6Mq5GgC7YoSZlUAChuhtV2hJF4urT0TZl3bxj8+R+ciIGhVqBAZeGdEFXLr1G8ov4JrKO/JFpZA",
	"Zim0kiCyDL2PkUUM/UxPmegLofTXYOo9ar1XeyyZaM50YdkwwuhRb0NUyKpnGHIr/RCMiBADn1EEDKIk",
	"8UAyZMMMwwrRwDS5wACl8H5lnZwmjL/T5DgXZoFT075I+c0qR8O7KC9mGqEyWplrZRYRLkpnS3RBxWhX",
	"kpyu+Rew8Pdp5zQuWZMJajARzgn+v+GlAzQzazWKqBmKcuXIUh/aT9MuEy0c29mvmEVAEDqrNOu3g0x9",
	"Oe616ZsSnTDsyLM/8C3RiJbt5BEhiWtfzRiukzQpKh1UqddJmki1VBKH00pX/HbjNBEJMXWv6L7SA5K7",
	"5jl+EkWpaYODJ6Pvkvs4qBcOkY0BsEMqs3IgG14EdjN6CXPrmpwYLMycMFkO1ozgNdcLGfusB2syBIca",
	"hUcZ/bLl/uT8/Oro3eXLq9PXPx+9On1+dXx+8vzk9eXp0auLXakoRoNQeiDA3qLbmyvUEpAE8inz10Yr",
	"x2/l0I+S9GG+z4p5zvSG3L9A78ViQEcvq0KYPSqCSFcjeP3mEkST8FMoxLrWDYgAwqwhqAJH99qQLdLS",
	"vdWWNcs7FmXtDFQFPVHuZiFucTcPL1HokF8EESq/y4Rvnm8CzF7fH0D1qiFyDULtkMKiVsOOvIrVQNgu",
	"QjJJqkrJIV8rnaX4dv14W1i70HivtXjLZochzl/Zhbod5BruW8reFmgN/qN+MspsMch2B5cbGTsIfDff",
	"kW5nlyHWz3AAlauQXxVt/rsrtLqp8iZtZW3Y3XCxIxy/uFqiU3OFg6nngeYdMteG6haRtC/bkEI2WWQH",
	"DI44wRdCg6mKGboUPJoAwlPXxKyANVBWrrQeR3AEP128eV1/Gxs2Cntqp0ygTmuurQjfP4UZzq1DRg+P",
	"juGWMNlVxsfKYDw6gL/BeHRIuwhNcLSempWzZgEzal9EgNIqE0ZwmSNoNIuQQyZKuEYsmT1lFho31TrM",
	"nS1AeCoupoawVbiZCk44pdeghSM4cyrkBQaVbcP8wZiTVCE+vWJCyeT7pwPWPUchlUHvj3PMrgeCYpOr",
	"trISBrDUs3I5ZK//PhfaY5OHhHMKPSgT0BmhIeaQ0ZB7xY6qG3Sl9WHh0A99ba8fUPvwlmkf5lrHaSS+",
	"DTAz0sTDC7YtDQ7krUEEpsS6cEKifDAYpxvWhsXilvRWdOu3rDsGfdEtLchTc6sll8+8gH4VHvUS/Qje",
	"d1pzW9B4IUzNDDNReex04K0bhOicu0IOSLFQPqD7fJDuOP7hd0/vAe3t5siooirg4JCqBioh0PkRxO0o",
	"uElG9n5XaZwAO4VXtJqf+KkpK59DibbUpMCVcNJD6VCqLJZzvpr5oEJFa3zUzlDi6AnxfZoUymz+Hxx+",
	"kbyyUTjKdx7dHfr+ayaKIZEuyWHfCjUgTexx2xjYleFTqRz6K2WGMC+zRnqoTFCafaDbMkO9dNRF4R/H",
	"44ZBZQIu0CU36X2xeDTjjEWI35mCTYjkGhxmqJbYzA9ha3xIecsHFDKFVa6yfHBWOBiPacL8XMXHLVg9",
	"Q+F6BdUtduopt7dZT69DJvuZ7Lk+IdveGvm3GW2Li/jZLhHCYcwqp8L6gpA7bjpj2ag4av+92HjnT+8v",
	"N7M9dmN+2+qNFB/HGMrM7a4ZL3Pl26ljDRveVi5Dnkm6KuQjeCmM1Og8CIewQIOOR1Sc+1WI014zNYoc",
	"qkATYmvFEC0tep5jFSJkOayU1vyX8EhpGuhOzfGbs7dHl6fPTl+dXv4bzt+9OrmAb5YH306mBmAPjqRU",
	"QS0jnI3gHAu7pApJADceaWyb4hMSOwXroBDXnW9oI4CNCUjOmcP6CyPh+BQckgl4EP2NFV6q+fzbUaRP",
	"hdAvVEf9Qo1jRXwAt1S0j4CymmmVNUocwRuTIYg6JKDynF3SyIIK9di8boNrEsd1pjp7d3EJwWpWMJBz",
	"R5I+xpW0EKMjswujfD0ODyrULcieKNWeD8IF9oElOh/NfDAaj8b1MMOIUiWT5MloPHrCyBtydrP9nFu0",
	"3+j3AsOur5xjqJzxcDgeU9jqmEdLZxlguJ5USxzBpa2ynK0OEks0Ek22JshpBh6nMpkk/8Twsqa4NX8+",
	"HI+/2CCv13cOzPPebrEfg7AqCuHWySR5pZZo6H3p7IzbO7HwFMJRWclH+nyfy+iHKa4tSMkN1h0NEQu8",
	"EQQbq3cITsznKhvU3Xmk+Yiq2y5ChwbEg/ySo303fvI1GTnaUuQmiay37NlsdbdBlwf71Nzta2rGGeZt",
	"hPu+GbhX55ok7R3JfRiWp/1kf+vI7uZjTBDowzMr119Mc71hwk0/DQVX4c0juk9b4tx31kH+8nQ8vm3D",
	"hsP9zsEULzn4CvN+bo0zhzxQEtrHxphPKZWHOLfOhKaYro/sELgAjIdJHqybGnq4KXFpGTfcKVhasVLc",
	"kSgPaCT33jDDzBZIyaXy6KaGEkHtd2CdyDhvRhU8uV9r7REWrTj88f4V2wdN3cIkmXz42I2ok0/11DIK",
	"Tem0kZTnAaZ/atNGnKiG4s1WoRtw23iztNcxG8IqtxrB2brayHKhTMqB/2vlQ6ctLB16PjmNhcrUZLZc",
	"QxD0DoXTqj3F5k3igEVICNaO4EivxNqDr7IMUfpJk9nJqiLASnCLWQUoKr/J7jOirSUXwB58oKrHq4Wh",
	"2sPErL2DJCT4H4WR/in1Y6HIVtt+s3tifDh+OtSLeE+WQSNR3u1DJrbxPq6420fqxuR2JznhxFp/BoUi",
	"+wgwuKr9gVzUU7Kom2QtwRocwdvoJ1wUTs1mpMAmbmZlvDBAgcJ4CCvLp/eK71awudPNAT9t5HBq+v4Z",
	"czz5sGQ2OkKTmvyQa9Tav2h083mZJv0fcqqvlIzOyUYo+0OjBUYMIb/ZujDTa2kJToavxFCOaHD6r5nd",
	"3plrY1cmrQcDMm2807q+y8e0N7eV4ybQGhLYryg78V2futup+3curtqjtqg49u67YCDaYeCKEqmW7BGj",
	"+OHpxNWDo9sruM1oqS7iHsfR++PCB5VhB1+cfD08G6rFssxWZDuHMQxe2waUqMTxvkI56RQ2nOhmCJsJ",
	"19TMlfMhhc18VVTB7tVXDihWLi7e1JVSoEOBEA8xuBXyYo7cD8UiSVuqpSIZgl06KkPzOVH0gHKnuW7E",
	"9dHh/Qt2rp3c5dXHrNa6DmJF81UjYQYqprvdmfW93mvGncMu3ZlTPZJHD0zCHuTUAzUCb9I40p818sH4",
	"8aHysjNA7cFj5e9zAEvxUXQsLqVDX185E/cAWdbe//C3G31zSwQfyeQDF3C+cju5ew9mcB4R33xOxr17",
	"Se8K3OfhRVv+0oxPhDqrNqel0L0gtHGOjTtY17pIgZ3R086g6Awfc0h0hoPXKivn6uGn+5Oq7WmIag/R",
	"ux5JOzN0KqruM54P87QGNgfyrc4KJF31I7Q/Vv/wkcrceGQeq+q+PJyWkjSpnK6H6pP9fX6YWx8mP4x/",
	"GHOhXFPcXt5MEYlhtxlBtVd169nTTbq9MCbvaM+0lo/2wA5sZhsXqTcT1eBWwypslxU4sOioccb2w44H",
	"3ny8+e8A",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
