//go:build go1.22

// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CalculationRequestOperation.
const (
	Add      CalculationRequestOperation = "add"
	Divide   CalculationRequestOperation = "divide"
	Multiply CalculationRequestOperation = "multiply"
	Subtract CalculationRequestOperation = "subtract"
)

// Valid indicates whether the value is a known member of the CalculationRequestOperation enum.
func (e CalculationRequestOperation) Valid() bool {
	switch e {
	case Add:
		return true
	case Divide:
		return true
	case Multiply:
		return true
	case Subtract:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatusStatus.
const (
	HealthStatusStatusOk HealthStatusStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatusStatus enum.
func (e HealthStatusStatus) Valid() bool {
	switch e {
	case HealthStatusStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for ReadinessStatusStatus.
const (
	ReadinessStatusStatusDegraded ReadinessStatusStatus = "degraded"
	ReadinessStatusStatusOk       ReadinessStatusStatus = "ok"
)

// Valid indicates whether the value is a known member of the ReadinessStatusStatus enum.
func (e ReadinessStatusStatus) Valid() bool {
	switch e {
	case ReadinessStatusStatusDegraded:
		return true
	case ReadinessStatusStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for TokenPairTokenType.
const (
	Bearer TokenPairTokenType = "Bearer"
)

// Valid indicates whether the value is a known member of the TokenPairTokenType enum.
func (e TokenPairTokenType) Valid() bool {
	switch e {
	case Bearer:
		return true
	default:
		return false
	}
}

// Defines values for ClientPlatform.
const (
	ClientPlatformAndroid ClientPlatform = "android"
	ClientPlatformIos     ClientPlatform = "ios"
	ClientPlatformWeb     ClientPlatform = "web"
)

// Valid indicates whether the value is a known member of the ClientPlatform enum.
func (e ClientPlatform) Valid() bool {
	switch e {
	case ClientPlatformAndroid:
		return true
	case ClientPlatformIos:
		return true
	case ClientPlatformWeb:
		return true
	default:
		return false
	}
}

// Defines values for LoginUserParamsXClientPlatform.
const (
	LoginUserParamsXClientPlatformAndroid LoginUserParamsXClientPlatform = "android"
	LoginUserParamsXClientPlatformIos     LoginUserParamsXClientPlatform = "ios"
	LoginUserParamsXClientPlatformWeb     LoginUserParamsXClientPlatform = "web"
)

// Valid indicates whether the value is a known member of the LoginUserParamsXClientPlatform enum.
func (e LoginUserParamsXClientPlatform) Valid() bool {
	switch e {
	case LoginUserParamsXClientPlatformAndroid:
		return true
	case LoginUserParamsXClientPlatformIos:
		return true
	case LoginUserParamsXClientPlatformWeb:
		return true
	default:
		return false
	}
}

// Defines values for RefreshSessionParamsXClientPlatform.
const (
	RefreshSessionParamsXClientPlatformAndroid RefreshSessionParamsXClientPlatform = "android"
	RefreshSessionParamsXClientPlatformIos     RefreshSessionParamsXClientPlatform = "ios"
	RefreshSessionParamsXClientPlatformWeb     RefreshSessionParamsXClientPlatform = "web"
)

// Valid indicates whether the value is a known member of the RefreshSessionParamsXClientPlatform enum.
func (e RefreshSessionParamsXClientPlatform) Valid() bool {
	switch e {
	case RefreshSessionParamsXClientPlatformAndroid:
		return true
	case RefreshSessionParamsXClientPlatformIos:
		return true
	case RefreshSessionParamsXClientPlatformWeb:
		return true
	default:
		return false
	}
}

// Defines values for SignInWithProviderTokenParamsXClientPlatform.
const (
	SignInWithProviderTokenParamsXClientPlatformAndroid SignInWithProviderTokenParamsXClientPlatform = "android"
	SignInWithProviderTokenParamsXClientPlatformIos     SignInWithProviderTokenParamsXClientPlatform = "ios"
	SignInWithProviderTokenParamsXClientPlatformWeb     SignInWithProviderTokenParamsXClientPlatform = "web"
)

// Valid indicates whether the value is a known member of the SignInWithProviderTokenParamsXClientPlatform enum.
func (e SignInWithProviderTokenParamsXClientPlatform) Valid() bool {
	switch e {
	case SignInWithProviderTokenParamsXClientPlatformAndroid:
		return true
	case SignInWithProviderTokenParamsXClientPlatformIos:
		return true
	case SignInWithProviderTokenParamsXClientPlatformWeb:
		return true
	default:
		return false
	}
}

// AuthMethods What the client needs to decide between "Set password" and "Change
// password", and when to disable unlinking.
type AuthMethods struct {
	Identities []Identity `json:"identities"`
	Password   bool       `json:"password"`
}

// CalculationRequest defines model for CalculationRequest.
type CalculationRequest struct {
	// A A decimal number, sent as a string on purpose. A JSON number is decoded
	// into a float64 before any server code runs, and 0.1 + 0.2 is already
	// wrong by that point. The length cap keeps a single request from asking
	// for arbitrarily large arithmetic.
	//
	//
	// Example: 10.5
	A Operand `json:"a"`

	// B A decimal number, sent as a string on purpose. A JSON number is decoded
	// into a float64 before any server code runs, and 0.1 + 0.2 is already
	// wrong by that point. The length cap keeps a single request from asking
	// for arbitrarily large arithmetic.
	//
	//
	// Example: 10.5
	B         Operand                     `json:"b"`
	Operation CalculationRequestOperation `json:"operation"`
}

// CalculationRequestOperation defines model for CalculationRequest.Operation.
type CalculationRequestOperation string

// CalculationResult defines model for CalculationResult.
type CalculationResult struct {
	// Result Example: 13.5
	Result string `json:"result"`
}

// Error defines model for Error.
type Error struct {
	// Code Stable code for clients to branch on. Never changes once released.
	//
	//
	// Example: ERR_AUTH_INVALID_CREDENTIALS
	Code string `json:"code"`

	// Details Per-field errors, for validation failures.
	Details *[]ErrorDetail `json:"details,omitempty"`

	// Message Human-readable. NOT a contract, may change at any time.
	Message string `json:"message"`
}

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	Field   string `json:"field"`
	Message string `json:"message"`
}

// HealthStatus defines model for HealthStatus.
type HealthStatus struct {
	Status HealthStatusStatus `json:"status"`
}

// HealthStatusStatus defines model for HealthStatus.Status.
type HealthStatusStatus string

// Identity defines model for Identity.
type Identity struct {
	Email *string            `json:"email,omitempty"`
	Id    openapi_types.UUID `json:"id"`

	// Provider Example: google
	Provider string `json:"provider"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	// Email Example: someone@example.com
	Email    string `json:"email"`
	Password string `json:"password"`
}

// Me defines model for Me.
type Me struct {
	// AuthMethods What the client needs to decide between "Set password" and "Change
	// password", and when to disable unlinking.
	AuthMethods   AuthMethods         `json:"auth_methods"`
	Email         openapi_types.Email `json:"email"`
	EmailVerified bool                `json:"email_verified"`
	Id            openapi_types.UUID  `json:"id"`
}

// Operand A decimal number, sent as a string on purpose. A JSON number is decoded
// into a float64 before any server code runs, and 0.1 + 0.2 is already
// wrong by that point. The length cap keeps a single request from asking
// for arbitrarily large arithmetic.
//
// Example: 10.5
type Operand = string

// ProviderInfo defines model for ProviderInfo.
type ProviderInfo struct {
	// Code Example: google
	Code string `json:"code"`

	// DisplayName Example: Google
	DisplayName string `json:"display_name"`
}

// ProviderTokenRequest defines model for ProviderTokenRequest.
type ProviderTokenRequest struct {
	IdToken string `json:"id_token"`
}

// ReadinessCheck defines model for ReadinessCheck.
type ReadinessCheck struct {
	// Error Set only when ok=false. Never carries internal detail.
	Error *string `json:"error,omitempty"`

	// Name Example: postgres
	Name string `json:"name"`
	Ok   bool   `json:"ok"`
}

// ReadinessStatus defines model for ReadinessStatus.
type ReadinessStatus struct {
	Checks []ReadinessCheck      `json:"checks"`
	Status ReadinessStatusStatus `json:"status"`
}

// ReadinessStatusStatus defines model for ReadinessStatus.Status.
type ReadinessStatusStatus string

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	// RefreshToken For clients that hold the token themselves. Web clients omit it
	// because the cookie carries it.
	RefreshToken *string `json:"refresh_token,omitempty"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	// Email Example: someone@example.com
	Email string `json:"email"`

	// Password Minimum 12 characters. Length is the only rule: composition rules
	// push people towards predictable substitutions.
	Password string `json:"password"`
}

// RegisteredUser defines model for RegisteredUser.
type RegisteredUser struct {
	Email         openapi_types.Email `json:"email"`
	EmailVerified bool                `json:"email_verified"`
	Id            openapi_types.UUID  `json:"id"`
}

// TokenPair defines model for TokenPair.
type TokenPair struct {
	AccessToken string `json:"access_token"`

	// ExpiresIn Seconds until the access token expires.
	//
	// Example: 900
	ExpiresIn int `json:"expires_in"`

	// RefreshToken Absent for web clients: they receive it in an httpOnly cookie
	// instead, which a script cannot read.
	RefreshToken *string            `json:"refresh_token,omitempty"`
	TokenType    TokenPairTokenType `json:"token_type"`
}

// TokenPairTokenType defines model for TokenPair.TokenType.
type TokenPairTokenType string

// VerifyEmailRequest defines model for VerifyEmailRequest.
type VerifyEmailRequest struct {
	Token string `json:"token"`
}

// ClientPlatform defines model for ClientPlatform.
type ClientPlatform string

// ProviderCode Example: google
type ProviderCode = string

// RefreshCookie defines model for RefreshCookie.
type RefreshCookie = string

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// NotImplemented defines model for NotImplemented.
type NotImplemented = Error

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// ValidationFailed defines model for ValidationFailed.
type ValidationFailed = Error

// LoginUserParams defines parameters for LoginUser.
type LoginUserParams struct {
	// XClientPlatform Decides how the refresh token is delivered. "web" gets it in an
	// httpOnly cookie and never in the response body, so a script cannot read
	// it. Anything else gets it in the body to put in secure storage.
	XClientPlatform *LoginUserParamsXClientPlatform `json:"X-Client-Platform,omitempty"`
}

// LoginUserParamsXClientPlatform defines parameters for LoginUser.
type LoginUserParamsXClientPlatform string

// LogoutParams defines parameters for Logout.
type LogoutParams struct {
	// RefreshToken Where web clients carry the refresh token. Declared here so the cookie
	// is part of the contract rather than an undocumented side channel.
	RefreshToken *RefreshCookie `form:"refresh_token,omitempty" json:"refresh_token,omitempty"`
}

// RefreshSessionParams defines parameters for RefreshSession.
type RefreshSessionParams struct {
	// XClientPlatform Decides how the refresh token is delivered. "web" gets it in an
	// httpOnly cookie and never in the response body, so a script cannot read
	// it. Anything else gets it in the body to put in secure storage.
	XClientPlatform *RefreshSessionParamsXClientPlatform `json:"X-Client-Platform,omitempty"`

	// RefreshToken Where web clients carry the refresh token. Declared here so the cookie
	// is part of the contract rather than an undocumented side channel.
	RefreshToken *RefreshCookie `form:"refresh_token,omitempty" json:"refresh_token,omitempty"`
}

// RefreshSessionParamsXClientPlatform defines parameters for RefreshSession.
type RefreshSessionParamsXClientPlatform string

// CompleteProviderSignInParams defines parameters for CompleteProviderSignIn.
type CompleteProviderSignInParams struct {
	State string `form:"state" json:"state"`
	Code  string `form:"code" json:"code"`
}

// StartProviderSignInParams defines parameters for StartProviderSignIn.
type StartProviderSignInParams struct {
	// RedirectTo Where to send the browser afterwards. Must be a path beginning with
	// a single slash: accepting a full URL here would make this an open
	// redirect.
	RedirectTo *string `form:"redirect_to,omitempty" json:"redirect_to,omitempty"`
}

// SignInWithProviderTokenParams defines parameters for SignInWithProviderToken.
type SignInWithProviderTokenParams struct {
	// XClientPlatform Decides how the refresh token is delivered. "web" gets it in an
	// httpOnly cookie and never in the response body, so a script cannot read
	// it. Anything else gets it in the body to put in secure storage.
	XClientPlatform *SignInWithProviderTokenParamsXClientPlatform `json:"X-Client-Platform,omitempty"`
}

// SignInWithProviderTokenParamsXClientPlatform defines parameters for SignInWithProviderToken.
type SignInWithProviderTokenParamsXClientPlatform string

// LoginUserJSONRequestBody defines body for LoginUser for application/json ContentType.
type LoginUserJSONRequestBody = LoginRequest

// LogoutJSONRequestBody defines body for Logout for application/json ContentType.
type LogoutJSONRequestBody = RefreshRequest

// RefreshSessionJSONRequestBody defines body for RefreshSession for application/json ContentType.
type RefreshSessionJSONRequestBody = RefreshRequest

// RegisterUserJSONRequestBody defines body for RegisterUser for application/json ContentType.
type RegisterUserJSONRequestBody = RegisterRequest

// VerifyEmailJSONRequestBody defines body for VerifyEmail for application/json ContentType.
type VerifyEmailJSONRequestBody = VerifyEmailRequest

// SignInWithProviderTokenJSONRequestBody defines body for SignInWithProviderToken for application/json ContentType.
type SignInWithProviderTokenJSONRequestBody = ProviderTokenRequest

// CalculateJSONRequestBody defines body for Calculate for application/json ContentType.
type CalculateJSONRequestBody = CalculationRequest

// LinkIdentityJSONRequestBody defines body for LinkIdentity for application/json ContentType.
type LinkIdentityJSONRequestBody = ProviderTokenRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetHealthz Liveness probe
	// (GET /healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)
	// GetReadyz Readiness probe
	// (GET /readyz)
	GetReadyz(w http.ResponseWriter, r *http.Request)
	// LoginUser Exchange email and password for an access token
	// (POST /v1/auth/login)
	LoginUser(w http.ResponseWriter, r *http.Request, params LoginUserParams)
	// Logout End the session
	// (POST /v1/auth/logout)
	Logout(w http.ResponseWriter, r *http.Request, params LogoutParams)
	// ListProviders Identity providers this server can actually serve
	// (GET /v1/auth/providers)
	ListProviders(w http.ResponseWriter, r *http.Request)
	// RefreshSession Rotate the refresh token and get a new access token
	// (POST /v1/auth/refresh)
	RefreshSession(w http.ResponseWriter, r *http.Request, params RefreshSessionParams)
	// RegisterUser Create an account with an email and password
	// (POST /v1/auth/register)
	RegisterUser(w http.ResponseWriter, r *http.Request)
	// VerifyEmail Confirm an email address with a token
	// (POST /v1/auth/verify-email)
	VerifyEmail(w http.ResponseWriter, r *http.Request)
	// CompleteProviderSignIn Finish the browser sign-in flow
	// (GET /v1/auth/{provider}/callback)
	CompleteProviderSignIn(w http.ResponseWriter, r *http.Request, provider ProviderCode, params CompleteProviderSignInParams)
	// StartProviderSignIn Begin the browser sign-in flow
	// (GET /v1/auth/{provider}/start)
	StartProviderSignIn(w http.ResponseWriter, r *http.Request, provider ProviderCode, params StartProviderSignInParams)
	// SignInWithProviderToken Sign in with an ID token obtained by a native app
	// (POST /v1/auth/{provider}/token)
	SignInWithProviderToken(w http.ResponseWriter, r *http.Request, provider ProviderCode, params SignInWithProviderTokenParams)
	// Calculate Evaluate one arithmetic operation
	// (POST /v1/calculations)
	Calculate(w http.ResponseWriter, r *http.Request)
	// GetMe The authenticated user and its active login methods
	// (GET /v1/me)
	GetMe(w http.ResponseWriter, r *http.Request)
	// ListIdentities Providers linked to this account
	// (GET /v1/me/identities)
	ListIdentities(w http.ResponseWriter, r *http.Request)
	// UnlinkIdentity Remove a provider from this account
	// (POST /v1/me/identities/{id}/unlink)
	UnlinkIdentity(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// LinkIdentity Link a provider to this account
	// (POST /v1/me/identities/{provider})
	LinkIdentity(w http.ResponseWriter, r *http.Request, provider ProviderCode)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReadyz operation middleware
func (siw *ServerInterfaceWrapper) GetReadyz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadyz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LoginUser operation middleware
func (siw *ServerInterfaceWrapper) LoginUser(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params LoginUserParams

	headers := r.Header

	// ------------- Optional header parameter "X-Client-Platform" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Client-Platform")]; found {
		var XClientPlatform LoginUserParamsXClientPlatform
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Client-Platform", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Client-Platform", valueList[0], &XClientPlatform, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Client-Platform", Err: err})
			return
		}

		params.XClientPlatform = &XClientPlatform

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LoginUser(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params LogoutParams

	{
		var cookie *http.Cookie

		if cookie, err = r.Cookie("refresh_token"); err == nil {
			var value RefreshCookie
			err = runtime.BindStyledParameterWithOptions("simple", "refresh_token", cookie.Value, &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationCookie, Explode: true, Required: false, Type: "string", Format: ""})
			if err != nil {
				siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "refresh_token", Err: err})
				return
			}
			params.RefreshToken = &value

		}
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListProviders operation middleware
func (siw *ServerInterfaceWrapper) ListProviders(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProviders(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RefreshSession operation middleware
func (siw *ServerInterfaceWrapper) RefreshSession(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params RefreshSessionParams

	headers := r.Header

	// ------------- Optional header parameter "X-Client-Platform" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Client-Platform")]; found {
		var XClientPlatform RefreshSessionParamsXClientPlatform
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Client-Platform", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Client-Platform", valueList[0], &XClientPlatform, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Client-Platform", Err: err})
			return
		}

		params.XClientPlatform = &XClientPlatform

	}

	{
		var cookie *http.Cookie

		if cookie, err = r.Cookie("refresh_token"); err == nil {
			var value RefreshCookie
			err = runtime.BindStyledParameterWithOptions("simple", "refresh_token", cookie.Value, &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationCookie, Explode: true, Required: false, Type: "string", Format: ""})
			if err != nil {
				siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "refresh_token", Err: err})
				return
			}
			params.RefreshToken = &value

		}
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RefreshSession(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RegisterUser operation middleware
func (siw *ServerInterfaceWrapper) RegisterUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// VerifyEmail operation middleware
func (siw *ServerInterfaceWrapper) VerifyEmail(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.VerifyEmail(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CompleteProviderSignIn operation middleware
func (siw *ServerInterfaceWrapper) CompleteProviderSignIn(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "provider" -------------
	var provider ProviderCode

	err = runtime.BindStyledParameterWithOptions("simple", "provider", r.PathValue("provider"), &provider, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "provider", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params CompleteProviderSignInParams

	// ------------- Required query parameter "state" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "state", r.URL.Query(), &params.State, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "state"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		}
		return
	}

	// ------------- Required query parameter "code" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "code", r.URL.Query(), &params.Code, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "code"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CompleteProviderSignIn(w, r, provider, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StartProviderSignIn operation middleware
func (siw *ServerInterfaceWrapper) StartProviderSignIn(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "provider" -------------
	var provider ProviderCode

	err = runtime.BindStyledParameterWithOptions("simple", "provider", r.PathValue("provider"), &provider, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "provider", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params StartProviderSignInParams

	// ------------- Optional query parameter "redirect_to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "redirect_to", r.URL.Query(), &params.RedirectTo, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "redirect_to"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "redirect_to", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartProviderSignIn(w, r, provider, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SignInWithProviderToken operation middleware
func (siw *ServerInterfaceWrapper) SignInWithProviderToken(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "provider" -------------
	var provider ProviderCode

	err = runtime.BindStyledParameterWithOptions("simple", "provider", r.PathValue("provider"), &provider, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "provider", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params SignInWithProviderTokenParams

	headers := r.Header

	// ------------- Optional header parameter "X-Client-Platform" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Client-Platform")]; found {
		var XClientPlatform SignInWithProviderTokenParamsXClientPlatform
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Client-Platform", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Client-Platform", valueList[0], &XClientPlatform, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Client-Platform", Err: err})
			return
		}

		params.XClientPlatform = &XClientPlatform

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SignInWithProviderToken(w, r, provider, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Calculate operation middleware
func (siw *ServerInterfaceWrapper) Calculate(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Calculate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListIdentities operation middleware
func (siw *ServerInterfaceWrapper) ListIdentities(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListIdentities(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UnlinkIdentity operation middleware
func (siw *ServerInterfaceWrapper) UnlinkIdentity(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UnlinkIdentity(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LinkIdentity operation middleware
func (siw *ServerInterfaceWrapper) LinkIdentity(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "provider" -------------
	var provider ProviderCode

	err = runtime.BindStyledParameterWithOptions("simple", "provider", r.PathValue("provider"), &provider, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "provider", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LinkIdentity(w, r, provider)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/auth/register", wrapper.RegisterUser)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/auth/login", wrapper.LoginUser)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/auth/refresh", wrapper.RefreshSession)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/auth/logout", wrapper.Logout)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/auth/providers", wrapper.ListProviders)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/auth/{provider}/start", wrapper.StartProviderSignIn)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/auth/{provider}/callback", wrapper.CompleteProviderSignIn)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/auth/{provider}/token", wrapper.SignInWithProviderToken)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/me/identities", wrapper.ListIdentities)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/me/identities/{provider}", wrapper.LinkIdentity)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/me/identities/{id}/unlink", wrapper.UnlinkIdentity)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/auth/verify-email", wrapper.VerifyEmail)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/me", wrapper.GetMe)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/calculations", wrapper.Calculate)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/healthz", wrapper.GetHealthz)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/readyz", wrapper.GetReadyz)

	return m
}

type BadRequestJSONResponse Error

type ConflictJSONResponse Error

type ForbiddenJSONResponse Error

type NotFoundJSONResponse Error

type NotImplementedJSONResponse Error

type TooManyRequestsJSONResponse Error

type UnauthorizedJSONResponse Error

type ValidationFailedJSONResponse Error

type GetHealthzRequestObject struct {
}

type GetHealthzResponseObject interface {
	VisitGetHealthzResponse(w http.ResponseWriter) error
}

type GetHealthz200JSONResponse HealthStatus

func (response GetHealthz200JSONResponse) VisitGetHealthzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadyzRequestObject struct {
}

type GetReadyzResponseObject interface {
	VisitGetReadyzResponse(w http.ResponseWriter) error
}

type GetReadyz200JSONResponse ReadinessStatus

func (response GetReadyz200JSONResponse) VisitGetReadyzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadyz503JSONResponse ReadinessStatus

func (response GetReadyz503JSONResponse) VisitGetReadyzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type LoginUserRequestObject struct {
	Params LoginUserParams
	Body   *LoginUserJSONRequestBody
}

type LoginUserResponseObject interface {
	VisitLoginUserResponse(w http.ResponseWriter) error
}

type LoginUser200JSONResponse TokenPair

func (response LoginUser200JSONResponse) VisitLoginUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type LoginUser400JSONResponse struct{ BadRequestJSONResponse }

func (response LoginUser400JSONResponse) VisitLoginUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type LoginUser401JSONResponse Error

func (response LoginUser401JSONResponse) VisitLoginUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type LoginUser403JSONResponse struct{ ForbiddenJSONResponse }

func (response LoginUser403JSONResponse) VisitLoginUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type LoginUser429JSONResponse struct{ TooManyRequestsJSONResponse }

func (response LoginUser429JSONResponse) VisitLoginUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type LogoutRequestObject struct {
	Params LogoutParams
	Body   *LogoutJSONRequestBody
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout204Response struct {
}

func (response Logout204Response) VisitLogoutResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type ListProvidersRequestObject struct {
}

type ListProvidersResponseObject interface {
	VisitListProvidersResponse(w http.ResponseWriter) error
}

type ListProviders200JSONResponse []ProviderInfo

func (response ListProviders200JSONResponse) VisitListProvidersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshSessionRequestObject struct {
	Params RefreshSessionParams
	Body   *RefreshSessionJSONRequestBody
}

type RefreshSessionResponseObject interface {
	VisitRefreshSessionResponse(w http.ResponseWriter) error
}

type RefreshSession200JSONResponse TokenPair

func (response RefreshSession200JSONResponse) VisitRefreshSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshSession400JSONResponse struct{ BadRequestJSONResponse }

func (response RefreshSession400JSONResponse) VisitRefreshSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshSession401JSONResponse Error

func (response RefreshSession401JSONResponse) VisitRefreshSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterUserRequestObject struct {
	Body *RegisterUserJSONRequestBody
}

type RegisterUserResponseObject interface {
	VisitRegisterUserResponse(w http.ResponseWriter) error
}

type RegisterUser201JSONResponse RegisteredUser

func (response RegisterUser201JSONResponse) VisitRegisterUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterUser400JSONResponse struct{ BadRequestJSONResponse }

func (response RegisterUser400JSONResponse) VisitRegisterUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterUser409JSONResponse struct{ ConflictJSONResponse }

func (response RegisterUser409JSONResponse) VisitRegisterUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterUser422JSONResponse struct{ ValidationFailedJSONResponse }

func (response RegisterUser422JSONResponse) VisitRegisterUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type VerifyEmailRequestObject struct {
	Body *VerifyEmailJSONRequestBody
}

type VerifyEmailResponseObject interface {
	VisitVerifyEmailResponse(w http.ResponseWriter) error
}

type VerifyEmail204Response struct {
}

func (response VerifyEmail204Response) VisitVerifyEmailResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type VerifyEmail400JSONResponse struct{ BadRequestJSONResponse }

func (response VerifyEmail400JSONResponse) VisitVerifyEmailResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type VerifyEmail410JSONResponse Error

func (response VerifyEmail410JSONResponse) VisitVerifyEmailResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(410)
	_, err := buf.WriteTo(w)
	return err
}

type CompleteProviderSignInRequestObject struct {
	Provider ProviderCode `json:"provider"`
	Params   CompleteProviderSignInParams
}

type CompleteProviderSignInResponseObject interface {
	VisitCompleteProviderSignInResponse(w http.ResponseWriter) error
}

type CompleteProviderSignIn302ResponseHeaders struct {
	Location *string
}

type CompleteProviderSignIn302Response struct {
	Headers CompleteProviderSignIn302ResponseHeaders
}

func (response CompleteProviderSignIn302Response) VisitCompleteProviderSignInResponse(w http.ResponseWriter) error {
	if response.Headers.Location != nil {
		w.Header().Set("Location", fmt.Sprint(*response.Headers.Location))
	}
	w.WriteHeader(302)
	return nil
}

type CompleteProviderSignIn400JSONResponse struct{ BadRequestJSONResponse }

func (response CompleteProviderSignIn400JSONResponse) VisitCompleteProviderSignInResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CompleteProviderSignIn403JSONResponse struct{ ForbiddenJSONResponse }

func (response CompleteProviderSignIn403JSONResponse) VisitCompleteProviderSignInResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CompleteProviderSignIn409JSONResponse struct{ ConflictJSONResponse }

func (response CompleteProviderSignIn409JSONResponse) VisitCompleteProviderSignInResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CompleteProviderSignIn501JSONResponse struct{ NotImplementedJSONResponse }

func (response CompleteProviderSignIn501JSONResponse) VisitCompleteProviderSignInResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(501)
	_, err := buf.WriteTo(w)
	return err
}

type StartProviderSignInRequestObject struct {
	Provider ProviderCode `json:"provider"`
	Params   StartProviderSignInParams
}

type StartProviderSignInResponseObject interface {
	VisitStartProviderSignInResponse(w http.ResponseWriter) error
}

type StartProviderSignIn302ResponseHeaders struct {
	Location *string
}

type StartProviderSignIn302Response struct {
	Headers StartProviderSignIn302ResponseHeaders
}

func (response StartProviderSignIn302Response) VisitStartProviderSignInResponse(w http.ResponseWriter) error {
	if response.Headers.Location != nil {
		w.Header().Set("Location", fmt.Sprint(*response.Headers.Location))
	}
	w.WriteHeader(302)
	return nil
}

type StartProviderSignIn501JSONResponse struct{ NotImplementedJSONResponse }

func (response StartProviderSignIn501JSONResponse) VisitStartProviderSignInResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(501)
	_, err := buf.WriteTo(w)
	return err
}

type SignInWithProviderTokenRequestObject struct {
	Provider ProviderCode `json:"provider"`
	Params   SignInWithProviderTokenParams
	Body     *SignInWithProviderTokenJSONRequestBody
}

type SignInWithProviderTokenResponseObject interface {
	VisitSignInWithProviderTokenResponse(w http.ResponseWriter) error
}

type SignInWithProviderToken200JSONResponse TokenPair

func (response SignInWithProviderToken200JSONResponse) VisitSignInWithProviderTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SignInWithProviderToken400JSONResponse struct{ BadRequestJSONResponse }

func (response SignInWithProviderToken400JSONResponse) VisitSignInWithProviderTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type SignInWithProviderToken401JSONResponse struct{ UnauthorizedJSONResponse }

func (response SignInWithProviderToken401JSONResponse) VisitSignInWithProviderTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type SignInWithProviderToken403JSONResponse struct{ ForbiddenJSONResponse }

func (response SignInWithProviderToken403JSONResponse) VisitSignInWithProviderTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type SignInWithProviderToken409JSONResponse struct{ ConflictJSONResponse }

func (response SignInWithProviderToken409JSONResponse) VisitSignInWithProviderTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type SignInWithProviderToken501JSONResponse struct{ NotImplementedJSONResponse }

func (response SignInWithProviderToken501JSONResponse) VisitSignInWithProviderTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(501)
	_, err := buf.WriteTo(w)
	return err
}

type CalculateRequestObject struct {
	Body *CalculateJSONRequestBody
}

type CalculateResponseObject interface {
	VisitCalculateResponse(w http.ResponseWriter) error
}

type Calculate200JSONResponse CalculationResult

func (response Calculate200JSONResponse) VisitCalculateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Calculate400JSONResponse struct{ BadRequestJSONResponse }

func (response Calculate400JSONResponse) VisitCalculateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type Calculate401JSONResponse struct{ UnauthorizedJSONResponse }

func (response Calculate401JSONResponse) VisitCalculateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type Calculate422JSONResponse struct{ ValidationFailedJSONResponse }

func (response Calculate422JSONResponse) VisitCalculateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type GetMeRequestObject struct {
}

type GetMeResponseObject interface {
	VisitGetMeResponse(w http.ResponseWriter) error
}

type GetMe200JSONResponse Me

func (response GetMe200JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMe401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetMe401JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListIdentitiesRequestObject struct {
}

type ListIdentitiesResponseObject interface {
	VisitListIdentitiesResponse(w http.ResponseWriter) error
}

type ListIdentities200JSONResponse []Identity

func (response ListIdentities200JSONResponse) VisitListIdentitiesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListIdentities401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListIdentities401JSONResponse) VisitListIdentitiesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UnlinkIdentityRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type UnlinkIdentityResponseObject interface {
	VisitUnlinkIdentityResponse(w http.ResponseWriter) error
}

type UnlinkIdentity204Response struct {
}

func (response UnlinkIdentity204Response) VisitUnlinkIdentityResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type UnlinkIdentity401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UnlinkIdentity401JSONResponse) VisitUnlinkIdentityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UnlinkIdentity404JSONResponse struct{ NotFoundJSONResponse }

func (response UnlinkIdentity404JSONResponse) VisitUnlinkIdentityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UnlinkIdentity409JSONResponse struct{ ConflictJSONResponse }

func (response UnlinkIdentity409JSONResponse) VisitUnlinkIdentityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type LinkIdentityRequestObject struct {
	Provider ProviderCode `json:"provider"`
	Body     *LinkIdentityJSONRequestBody
}

type LinkIdentityResponseObject interface {
	VisitLinkIdentityResponse(w http.ResponseWriter) error
}

type LinkIdentity201JSONResponse Identity

func (response LinkIdentity201JSONResponse) VisitLinkIdentityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type LinkIdentity401JSONResponse struct{ UnauthorizedJSONResponse }

func (response LinkIdentity401JSONResponse) VisitLinkIdentityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type LinkIdentity403JSONResponse struct{ ForbiddenJSONResponse }

func (response LinkIdentity403JSONResponse) VisitLinkIdentityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type LinkIdentity409JSONResponse struct{ ConflictJSONResponse }

func (response LinkIdentity409JSONResponse) VisitLinkIdentityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type LinkIdentity501JSONResponse struct{ NotImplementedJSONResponse }

func (response LinkIdentity501JSONResponse) VisitLinkIdentityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(501)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetHealthz Liveness probe
	// (GET /healthz)
	GetHealthz(ctx context.Context, request GetHealthzRequestObject) (GetHealthzResponseObject, error)
	// GetReadyz Readiness probe
	// (GET /readyz)
	GetReadyz(ctx context.Context, request GetReadyzRequestObject) (GetReadyzResponseObject, error)
	// LoginUser Exchange email and password for an access token
	// (POST /v1/auth/login)
	LoginUser(ctx context.Context, request LoginUserRequestObject) (LoginUserResponseObject, error)
	// Logout End the session
	// (POST /v1/auth/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// ListProviders Identity providers this server can actually serve
	// (GET /v1/auth/providers)
	ListProviders(ctx context.Context, request ListProvidersRequestObject) (ListProvidersResponseObject, error)
	// RefreshSession Rotate the refresh token and get a new access token
	// (POST /v1/auth/refresh)
	RefreshSession(ctx context.Context, request RefreshSessionRequestObject) (RefreshSessionResponseObject, error)
	// RegisterUser Create an account with an email and password
	// (POST /v1/auth/register)
	RegisterUser(ctx context.Context, request RegisterUserRequestObject) (RegisterUserResponseObject, error)
	// VerifyEmail Confirm an email address with a token
	// (POST /v1/auth/verify-email)
	VerifyEmail(ctx context.Context, request VerifyEmailRequestObject) (VerifyEmailResponseObject, error)
	// CompleteProviderSignIn Finish the browser sign-in flow
	// (GET /v1/auth/{provider}/callback)
	CompleteProviderSignIn(ctx context.Context, request CompleteProviderSignInRequestObject) (CompleteProviderSignInResponseObject, error)
	// StartProviderSignIn Begin the browser sign-in flow
	// (GET /v1/auth/{provider}/start)
	StartProviderSignIn(ctx context.Context, request StartProviderSignInRequestObject) (StartProviderSignInResponseObject, error)
	// SignInWithProviderToken Sign in with an ID token obtained by a native app
	// (POST /v1/auth/{provider}/token)
	SignInWithProviderToken(ctx context.Context, request SignInWithProviderTokenRequestObject) (SignInWithProviderTokenResponseObject, error)
	// Calculate Evaluate one arithmetic operation
	// (POST /v1/calculations)
	Calculate(ctx context.Context, request CalculateRequestObject) (CalculateResponseObject, error)
	// GetMe The authenticated user and its active login methods
	// (GET /v1/me)
	GetMe(ctx context.Context, request GetMeRequestObject) (GetMeResponseObject, error)
	// ListIdentities Providers linked to this account
	// (GET /v1/me/identities)
	ListIdentities(ctx context.Context, request ListIdentitiesRequestObject) (ListIdentitiesResponseObject, error)
	// UnlinkIdentity Remove a provider from this account
	// (POST /v1/me/identities/{id}/unlink)
	UnlinkIdentity(ctx context.Context, request UnlinkIdentityRequestObject) (UnlinkIdentityResponseObject, error)
	// LinkIdentity Link a provider to this account
	// (POST /v1/me/identities/{provider})
	LinkIdentity(ctx context.Context, request LinkIdentityRequestObject) (LinkIdentityResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetHealthz operation middleware
func (sh *strictHandler) GetHealthz(w http.ResponseWriter, r *http.Request) {
	var request GetHealthzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealthz(ctx, request.(GetHealthzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealthz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthzResponseObject); ok {
		if err := validResponse.VisitGetHealthzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetReadyz operation middleware
func (sh *strictHandler) GetReadyz(w http.ResponseWriter, r *http.Request) {
	var request GetReadyzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetReadyz(ctx, request.(GetReadyzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReadyz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetReadyzResponseObject); ok {
		if err := validResponse.VisitGetReadyzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// LoginUser operation middleware
func (sh *strictHandler) LoginUser(w http.ResponseWriter, r *http.Request, params LoginUserParams) {
	var request LoginUserRequestObject

	request.Params = params

	var body LoginUserJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.LoginUser(ctx, request.(LoginUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LoginUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LoginUserResponseObject); ok {
		if err := validResponse.VisitLoginUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Logout operation middleware
func (sh *strictHandler) Logout(w http.ResponseWriter, r *http.Request, params LogoutParams) {
	var request LogoutRequestObject

	request.Params = params

	var body LogoutJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		if !errors.Is(err, io.EOF) {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
			return
		}
	} else {
		request.Body = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx, request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		if err := validResponse.VisitLogoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListProviders operation middleware
func (sh *strictHandler) ListProviders(w http.ResponseWriter, r *http.Request) {
	var request ListProvidersRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListProviders(ctx, request.(ListProvidersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListProviders")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListProvidersResponseObject); ok {
		if err := validResponse.VisitListProvidersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RefreshSession operation middleware
func (sh *strictHandler) RefreshSession(w http.ResponseWriter, r *http.Request, params RefreshSessionParams) {
	var request RefreshSessionRequestObject

	request.Params = params

	var body RefreshSessionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		if !errors.Is(err, io.EOF) {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
			return
		}
	} else {
		request.Body = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RefreshSession(ctx, request.(RefreshSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RefreshSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RefreshSessionResponseObject); ok {
		if err := validResponse.VisitRefreshSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RegisterUser operation middleware
func (sh *strictHandler) RegisterUser(w http.ResponseWriter, r *http.Request) {
	var request RegisterUserRequestObject

	var body RegisterUserJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RegisterUser(ctx, request.(RegisterUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RegisterUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RegisterUserResponseObject); ok {
		if err := validResponse.VisitRegisterUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// VerifyEmail operation middleware
func (sh *strictHandler) VerifyEmail(w http.ResponseWriter, r *http.Request) {
	var request VerifyEmailRequestObject

	var body VerifyEmailJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.VerifyEmail(ctx, request.(VerifyEmailRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "VerifyEmail")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(VerifyEmailResponseObject); ok {
		if err := validResponse.VisitVerifyEmailResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CompleteProviderSignIn operation middleware
func (sh *strictHandler) CompleteProviderSignIn(w http.ResponseWriter, r *http.Request, provider ProviderCode, params CompleteProviderSignInParams) {
	var request CompleteProviderSignInRequestObject

	request.Provider = provider
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CompleteProviderSignIn(ctx, request.(CompleteProviderSignInRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CompleteProviderSignIn")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CompleteProviderSignInResponseObject); ok {
		if err := validResponse.VisitCompleteProviderSignInResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// StartProviderSignIn operation middleware
func (sh *strictHandler) StartProviderSignIn(w http.ResponseWriter, r *http.Request, provider ProviderCode, params StartProviderSignInParams) {
	var request StartProviderSignInRequestObject

	request.Provider = provider
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.StartProviderSignIn(ctx, request.(StartProviderSignInRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StartProviderSignIn")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(StartProviderSignInResponseObject); ok {
		if err := validResponse.VisitStartProviderSignInResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SignInWithProviderToken operation middleware
func (sh *strictHandler) SignInWithProviderToken(w http.ResponseWriter, r *http.Request, provider ProviderCode, params SignInWithProviderTokenParams) {
	var request SignInWithProviderTokenRequestObject

	request.Provider = provider
	request.Params = params

	var body SignInWithProviderTokenJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SignInWithProviderToken(ctx, request.(SignInWithProviderTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SignInWithProviderToken")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SignInWithProviderTokenResponseObject); ok {
		if err := validResponse.VisitSignInWithProviderTokenResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Calculate operation middleware
func (sh *strictHandler) Calculate(w http.ResponseWriter, r *http.Request) {
	var request CalculateRequestObject

	var body CalculateJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Calculate(ctx, request.(CalculateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Calculate")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CalculateResponseObject); ok {
		if err := validResponse.VisitCalculateResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMe operation middleware
func (sh *strictHandler) GetMe(w http.ResponseWriter, r *http.Request) {
	var request GetMeRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMe(ctx, request.(GetMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMeResponseObject); ok {
		if err := validResponse.VisitGetMeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListIdentities operation middleware
func (sh *strictHandler) ListIdentities(w http.ResponseWriter, r *http.Request) {
	var request ListIdentitiesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListIdentities(ctx, request.(ListIdentitiesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListIdentities")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListIdentitiesResponseObject); ok {
		if err := validResponse.VisitListIdentitiesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UnlinkIdentity operation middleware
func (sh *strictHandler) UnlinkIdentity(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request UnlinkIdentityRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UnlinkIdentity(ctx, request.(UnlinkIdentityRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UnlinkIdentity")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UnlinkIdentityResponseObject); ok {
		if err := validResponse.VisitUnlinkIdentityResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// LinkIdentity operation middleware
func (sh *strictHandler) LinkIdentity(w http.ResponseWriter, r *http.Request, provider ProviderCode) {
	var request LinkIdentityRequestObject

	request.Provider = provider

	var body LinkIdentityJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.LinkIdentity(ctx, request.(LinkIdentityRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LinkIdentity")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LinkIdentityResponseObject); ok {
		if err := validResponse.VisitLinkIdentityResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"3Ft7c9s4kv8qXbz7Y7eOluUks7Wrq6s6x0luvOs8ynZm7mqUykJES8SYBDgAaEWb8ne/6gb4kijbedg1",
	"u//ZFAk0+vnrBz4nmSkro1F7l8w+J5WwokSPlv87KRRq/64QfmlsSU8kusyqyiujk1nyAjMl0UFu1uBz",
	"BItLiy4Hb65Qg3IgsVDXaFFOYJ6scTFPYIXegfKgNAg917n31VtdbCAz5kohCC1B4zVaeiGs6SqjHcLC",
	"yE0KzoCAQANkQmvjwaKQc638BI71xudKrwALh/2dfB6+B2+gqvmRw6y2CM4bK1Y4meskTRQdKkch0SZp",
	"okWJySz534PAhoOWD2nishxLQQxBXZfJ7Bc6HC1gXJImQktrlEw+pInfVLSG81bpVXJzkybvrLlWEu2J",
	"kbjL0eZXyIzEFISDQjmPEhYbOLw+OhS1zw+r+JKbNDRXwucdxc3vSZpY/K1WFmUy87bGAeGfRFkV9PrK",
	"mFWByRix50GgJyybXWp/ztEirHEBGbPIQSas3ezqwgReYFYIixL4E2f4nSDzuVYOKmE9mGV8rL0VmQcr",
	"fI4WfC5IWaDW0mR1iZoY4pREyHKhNRY96YUlO15EMj4yGQPJbZ/2Jk0aXWPlfy7kOf5Wo/P0H9GEmv8U",
	"VVWoTBAPDn91xIjPvWX/3eIymSX/dtgZ1mH41R2+tNbYsNWQka9FQZqFEmzc8iZNToxeFip7hO2bnRys",
	"lc8BPynnyYycFx6JlFfGLpSUqB+eluPa56g9rUpqX3sgGxdFYdYoiZY3xr8ytZYPT8obA67OcmCfkoKx",
	"TMrG1NZFQk7JhIJCPgY5nkxjqVY1GZIht6YcOLTXaImgS2NeC72JWusenqJz4REKVSofRPNek38yVv3j",
	"MfjxWjlHWmooVlyLQkkQWYbOBZ9DBP1ET3nTV0IVj0HUz1gUB9GWSXmXvC9ct4SwX43L0C6k76/R50a6",
	"MQcrfHCJ7F9BI0o6HkiOvLBAv0bUME8u0EMlnFsbK+cJh9F5cpILvcK57n5I+Zd1jppXUU4sCoRaF0pf",
	"Kb0KjrSypkLrVfCDSpI5tv95LN1d3DkNn2xIBNHNCmsF/9/Q0nPBC2MKFIEzXcD6pXs17RPRRVWz+BWz",
	"4CpFkdUF87fns4fnuFOmbyu0QrMiL77gXdojSLYHB4Qkql294ECWpElZF15VxSZJE6koOo+jg/7xu4XT",
	"RCRE1J1Hd3UxcnLbPu+C/tHTyQ/JXRTED8e2DQaws1U2imouPKsZ/QhLY1u04A0srNBZDkZP4A3Dvox1",
	"1oHRGYLFAoVDGfSyo/7l+fnH4/eXP348ffPT8dnpi48n5y9fvHxzeXp8drF7KrJRL1QxYmDv0B4sFRYS",
	"kA7kUqavs1a239pigFr30X1mzAveb0z9S3ROrEZ49GNdCn1AWJZ4NYE3by9BtFAohVJsIm9AeBB6A16V",
	"OLlThiyRbt+9sowk70iUuTOClwZHuZ2EsMTtNPyIovD5hRe+drtEuPZ5Y2Dm6m4Dil+Nbdd6qJ2tsIxs",
	"2DmvYjaQbxc+mSV1reSYrrXo+74gu08yL9muMEb5mVmp/U6upb7b2ZkSjcb/jk8mmSlHye755faMPQ98",
	"O91h394qY6S/xhGvXPv8Y9nFv9tMqx8qb9LurC25DRU7h+MfPl6jVUuFo6HnnuIdE1ez69Ym6fBsYwxp",
	"osiOMzjmAF+KAnRdLtCm4FB7SgcFBFII/lW1rYzDCRzDXy/evonvhrybzJ6yYu0pYV4WRvg/PYMFLo1F",
	"9h4BNgafbGvtAjKYTo7gP2A6eUKriILc0Wau19boFaWgnvBIZZT2E7jMEQrUK59DJiq4QqyYPKVXBTZ5",
	"DCytKUE4AhdzTb5V2IXyVlhVbKAQltyZVT4v0ats280fTTlIleLTGW+UzP70bES6TdJ8qpdmf0i62xYp",
	"NLuqEJuPIXnsf/M/97Pf6G0H64xJviH5kpDqXmtWMuatd7rY9s2xzc5RSKXRuZMcs6vdbbCJ5VtRGz0Y",
	"Ks0wXDRX/7UUhcM2TgtrFTpQ2qPVooAQYydjbN1lZ2WcX1l0Y2+bq3tgQ14yHYaBkRPvCygZceL+gHaL",
	"gyNxfTRCEfBYWSFR3jtYpQ1p48fiYsZefRkWO3YE+qoPvciSc1NITi/4A/qrdFhco5vAz72ijimpiubn",
	"eoGZqB32ajedGvhgvLuHHDnFSjmP9tuDWM8xPPnh2R1BbTt51KqsSzh6QqiKIBbV0yAsR86Pzsjab+sC",
	"Z8BK4RR9zU/cXFe1y6FCUxXEwLWw0kFlUaoswF1XL5xXvqZvXODOWGAdHOJPaVIq3fx/9OS7xN2G4Sjf",
	"O7S38Pv3GUjHjsR+851QI6cJNYC9jpPiS6Usuo9Kj/m8zGjpoNZeFawD/ZICxE8n/Sj1l+m0JVBpj6tQ",
	"jLnDFo8XHNEpIvbqpzPacgMWM1TX2JbJYatKTnHdeRQyhXWusny0JD5qj2nC9HwMjztn9RyFHQDOPXIa",
	"MHew2ICvYyL7ieS5eUmy3Wv594x2+0Id+WHMaqv85oI8d1h0wWcj8Nj996rRzr/+fNlUhVmN+deOb8T4",
	"UOZREVwMxXhJFbi2Xh3dhjO1zZCr2bb2+QR+FFoWaB0Ii7BCjZaLm4yNlA9NDT3XqqkmhtSTXbQ06Ljs",
	"WAqf5bBWRcH/kj9SBfUt5vrk7et3x5enz0/PTi//D87fn728gD9cH/1xNtcAB3AspfLqOrizCZxjaa4J",
	"QQrgxCwNaWV4QsfmSmcprnrv0EIAjQjonAuL8Q0t4eQULJIIuN/yByOcVMvlHydhfwKKfydg9HdKrGui",
	"AzjlpHUEVPWiUFnLxAm81RmCiCYBtePokgYSlI/doVgmiFucxEj1+v3FJXhTMIOBlDts6YJdSQPBOjKz",
	"0srFro9XPsLCA1GpA+eF9awD12hdEPPRZDqZxmKPFpVKZsnTyXTylD2vz1nNDnNOYf9Bf6/Q7+rKOfra",
	"agdPplMy2yLE0coadjCMt9U1TuDS1FnOUgeJFWqJOtuQy2kLQqeSECn6H+OOW52LJ9Ppdyt0DvLykXrn",
	"uy3ygxHWZSnsJpklZ+oaNf1eWbNg+CxWjkw4MCv5QK8fcppxP8Z1gJTUYNPjEJHAC4E3IbsBb8VyqbJR",
	"3p2HPR+QddsgdKyAPkovKdoP06ePScjxFiObILLZkme71O0CbTqVBRUr2M2b4O6HYuBaBmOSdNB5/mX8",
	"PN0rh1ud6ZsPIUCg88+N3Hw3zg2KLTc3N9sN1ZsHVJ8O4tzVJSN9eTad7luwpfCw19LkT44eoR/CpYPM",
	"IhfcROFC4YCb8cpBqOtnoiCbjs1eBAaAoQ3pwNi5pocNxKXPuCCRgqEv1oozEuUAteTaBCwwMyVScKkd",
	"2rmmQBD1DowVGcfNwIKnd3Ota37SF0/+cvcX2424PjBJZr986FvUy0+xqhsOTeG0PSnXS/Swq9VZnKjH",
	"7M3Uvm9w2/7m2lyFaAjr3BQI1kS0keVC6ZQN/9fa+V5aWFl03OIMQGWuM1NtwAv6DYUtVDeswYuEApSQ",
	"4I2ZwHGxFhtHjdQMUbpZG9lJqsLDWnCKWXsoa9dE9wXtXUgGwA6cJ9Tj1EoT9tAhau94Ejr4l7qR4XzD",
	"Q3mRrbT9ZnfW4Mn02Vgu4hxJBrVEebsO6ZDGu/DF7TrSTo/sjbfPjc8BNSWxspGsFF4shAsDOnu70HE+",
	"pxFwEKalAxD4pYaob4BtzFTWxl6NClQ5/66l9Bvd7L1qPIMq4k6FZxT5ROpuE03TaICW7X1+ERdAZL4W",
	"RRFLsrcLL2aV+y38JaOi+BqUioxLgMZ1NGYSn6NIHyscBYkQJ/AuGDkj+rlu6kFsn20hmD/0UKLQDvza",
	"8NCO4vkvttW0meuhhSzO9dC5BIBGDkgyGT2NJR13Y2oQTeeiVexvgwnpP5FHeCQkcU4yQjms+K0wBADS",
	"m62hvkE9gmLB+NgeBfg2yP4+ocl7faXNWqexqiPTVjuNHap8wCxLU1vO4I2mA7s1QYuev2tcGiPjro8c",
	"GMfafZujCHIYGaMk1pI8ghXfHwvYWPXbD7+bumBE4A+j6MNa770w9NF33z5WPseAdJaZmmRnMZgBDX1F",
	"p0T41Lka5ayHShmlLBCa8uRcL5V1PoWmOC5qbw7iPA3ZysXF2whzPXW8fOjQcR7rxBI5mQ0ItzAEhMM2",
	"5HYpZKD+Fiu6B1ZtpwwZ3D65+4OdmarbtPqE2RpBLDOaJwyFHoG7t6sz83tz0Naqx1W6V2R8II0eKWPe",
	"S6lHAB4v0irS1wr5aPrwrvKyV/0euMfa3aUABBVt2ZO4lBZdnDQV93FknxvodHOYiaJYiOxqL3S9QO8G",
	"PrQXnyxKZblISUuAD1hFVFVw733POtdxeH1ByoXFhvOiqhBZh4jfn59R+R0t1+nXpqYhIi2hruiNhTVr",
	"zj1z5byxm0jBEq1FC2HG3M0aCoAO5mAb5hGNK+7C4hg4OjFUMPbYINELtdKnXw6SBhPpBJF4kPq3Gu2m",
	"m6MOo8C3DZTvlOzHF4od8vuv82HLlJ5On4wltkG226JNg56NaIRDn6Rx2J/XPTNZO8a3n5qbr3XFX1xo",
	"+FLn/cP06O4PtmaWb7PcV0orF1gXlZlT8AOlaZxkfW+b5Xr6LbXdzNiYjLCOUQmCGwBawru/nbxs/KNt",
	"Uian6GaEz1F3Fk0ZS1NN522DSfOC8R4KemwGX6lQER0JFzld24SZ60xUnhPb9o3352cNslsgWKTBDpRj",
	"9nhBJ/3exjh244ILxloOZCOWHi03oSfwOmIUAdSdgAWulNYER8gY5rod0nGFcPmMPV/lY7unLgo+crja",
	"wV6tFFexwiY0mIrcY8P53s2LLTtv3vjoTfL9zHtLzF9rwd/bVp4Th7/dVNr253huT/MbWnArbzDGsTL9",
	"ch13FftMgosXf5vATy1eXWyYOkF6ngaEa1MQtVTIhkdXLQrlPJsgx/wNm5PF0BkIBjrX/GQwEhLSoKA0",
	"CwRXV1WxIb1aUEXJ8V0xs2Rr4771XBONocFJdyz+c8BCYl3bUvVU8UXLCj1qe2xuPyufD0arvt3+fh+N",
	"iNF5sX/RhsTtnwzumPxzRlbSVcKITSp0+iKarll4oXS47ScaUxdVtdeBZN3wv9ufFDVXBPCBUqKR2xeP",
	"rJq7lyBGm63hl0fUza/Pp7vaPg0wCB+rTu2oLPRvhzTK0aiDsZ2KlNjDXjtd8Nf4kB3w1zh627C2Nk52",
	"2K9k7YBDnLwNbg3WDIg01aQdldfJjLgVDc00dsczGtDteHU4vO00yjZqTZx2rz1Gb2L/hapd9p4pTTXM",
	"3kG+A4/bZgcUYXlvIiIMZZ37MPTws5I3h+Gu2W0tymXtGqiu/HAUk0oIAciKMDYRPOkELsJ8KDU15zp2",
	"CuuqKTK0SKgrUzuuqLad1oBZun5yYbKrue4GYrlBWaEtBTGt2IxBkPd8slZUO8hj5KY2jz3uT4XvmqH8",
	"cJ8qUyAL5VeqAX307F7hL9zK/fIAuzVgUppr7Mss4tkv1bUWVe9XtTd8m1KbWJkKg9ezNj9EC3mv+UUL",
	"ogyDZGYd2p5zHWkK+Wat1W81gtISP/EFjb7euZqnFHl8gVC786ZyYDTOdfdeWA0WyNmY9yLLo7GtDbs1",
	"N94svU3vvgjx/u7w6/drBnROdJ/T/JcEob1ZPH3VN6y7XPgQwQ7naH/5QJoSKjJBy4b85FZGkia1LeIU",
	"7ezwkB/mxvnZn6d/nrKuxR0/74gjjg2GqmmcOev8Zhw2262PhIZPMI00xnxaA3ul9qyBTXExUY8uNQ4r",
	"us/KsfrMcQvQuhd7qOzmw83/DwA=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
